tier4/driving_log_replayer_v2

log_evaluator/launch/log_evaluator.launch.py
=> fix: set output directory

docs/use_case/annotationless_perception.en.md, docs/use_case/annotationless_perception.ja.md, docs/use_case/ar_tag_based_localizer.en.md, docs/use_case/ar_tag_based_localizer.ja.md, docs/use_case/eagleye.en.md, docs/use_case/eagleye.ja.md, docs/use_case/localization.en.md, docs/use_case/localization.ja.md, docs/use_case/perception.en.md, docs/use_case/perception.ja.md, docs/use_case/perception_2d.en.md, docs/use_case/perception_2d.ja.md, docs/use_case/performance_diag.en.md, docs/use_case/performance_diag.ja.md, docs/use_case/traffic_light.en.md, docs/use_case/traffic_light.ja.md, docs/use_case/yabloc.en.md, docs/use_case/yabloc.ja.md, log_evaluator/log_evaluator/launch_config.py
- document update
- fix annotationless_perception launch argument
=> chore: update  launch argument

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> feat: set dataset index

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- add argument `t4_dataset_path`
```shell
❯ ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=$HOME/dlr2_data/localization/scenario.yaml
[INFO] [launch]: All log files can be found below /home/hyt/.ros/log/2024-09-06-15-30-50-464432-dpc2405001-1290894
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [launch.user]: t4_dataset_path=PosixPath('/home/hyt/dlr2_data/localization/bag_only_dataset'), dataset_index=0, output_dir=PosixPath('/home/hyt/dlr2_data/localization/out/2024-0906-153050'), use_case=localization
[INFO] [launch.user]: check_launch_component(conf)={'sensing': 'true', 'localization': 'true', 'perception': 'false', 'planning': 'false', 'control': 'false'}
[INFO] [launch.user]: conf.get('initial_pose')='{"position": {"x": …
```
=> feat: add argument t4_dataset_path for compatibility with v1

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> feat: add t4_dataset_id

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- Check if include is required before including autoware's launch file
- If not, output LogInfo.
```shell
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scneario_path:=${secnario_path}
```
autoware_map_height_fitter is required when using localization
If it is not localization, there is no need to load it.
=> feat(launch): Output message if module is not launched

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- record multi perception objects
- add `record_only` `override_topics_regex` argument
```shell
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=$HOME/dlr2_data/x2_multi/scenario.yaml record_only:=true override_topics_regex:=\^/tf\$\|/sensing/lidar/concatenated/pointcloud\|\^/perception/.\*/objects\$
```
=> feat: support record only mode

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py, driving_log_replayer_v2/test/unittest/test_annotationless_perception.py
=> fix: get launch context

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- Allow users to add bag play remap with argument `remap`
```shell
❯ ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=$HOME/dlr2_data/localization/unlabeled.yaml remap:=/sensing/gnss/ublox/fix_velocity,/sensing/gnss/ublox/nav_sat_fix
```
It shows what is being remapped.
See remap_command is ['--remap',  ...]
driving_log_replayer adds the topic to be remapped according to the use case, and the topic to be remapped specified by the user is displayed.
```shell
[INFO] [launch]: All log files can be found below /home/hyt/.ros/log/2024-11-07-16-52-56-190738-dpc2405001-1683141
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [launch.user]: t4_dataset_path=PosixPath('/home/hyt/dlr2_data/localization/bag_only_dataset'), dataset_index=0, …
```
=> feat: bag play remap

driving_log_replayer_v2/driving_log_replayer_v2/launch_config.py
When testing aeb, it is absolutely use_aeb_autoware_state_check:=false, so it is automatically set in launch in driving_log_replayer_v2
1. use pilot-auto main
2. replace universe with https://github.com/tier4/autoware.universe/tree/feat/set-global-param-for-aeb-state-check
3. replace launch with https://github.com/autowarefoundation/autoware_launch/pull/1218
4. use driving_log_replayer_v2 https://github.com/tier4/driving_log_replayer_v2/tree/feat/aeb-state-check
```shell
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=${your_planning_control_scenario}
```
I checked AEB deubg marker published like the attached picture.
=> feat: set use_aeb_autoware_state_check

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- use sleep and on_exit bag play
```shell
git checkout feat/bag-play-delay-using-sleep
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=${your_scenario}
```
`/clock` is published before topics in bag play replaying.
https://github.com/user-attachments/assets/cded08b9-5e81-4968-941a-d9a650845041
`/clock` is published same timing as topics in bag published.
https://github.com/user-attachments/assets/e1ee8585-35c2-4a48-a766-969445dc16b4
closes: #49
=> feat: use cmd sleep for delay

driving_log_replayer_v2/driving_log_replayer_v2/launch/annotationless_perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/obstacle_segmentation.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception_2d.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/planning_control.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/traffic_light.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py, driving_log_replayer_v2/test/unittest/launch/test_launch_config.py
- Why this PR is needed
- It is useful if developers can see resource (CPU, memory, etc.) usage at each PR/release
- What this PR changes
- This PR enables `system_monitor` module, which measures resource usage/erros, and add `/diagnostics` topic to rosbag
I confirmed the followings
- system_monitor component is launched
- `/diagnostics` topic is recorded into rosbag
```
$ ros2 bag info Pn_UCv2.0_Motorcycle_Rotation_sp_issue60_case_d203d1ae-38f8-5ab9-a38d-98b9401a4a03.bag/
Files:             result_bag_0.db3
Bag size:          3.0 GiB
Storage id:        sqlite3
Duration:          55.616s
Start:             Sep 13 2022 13:53:41.995 (1663044821.995)
End:               Sep 13 2022 13:54:37.612 (1663044877.612)
Messages:          30636
Topic information: Topic: …
```
=> feat: enable system_monitor

docs/use_case/ground_segmentation.en.md, docs/use_case/ground_segmentation.ja.md, driving_log_replayer_v2/driving_log_replayer_v2/launch/ground_segmentation.py
Add document for ground segmentation evaluator
=> docs: add ground segmentation

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.0.2

driving_log_replayer_v2/scripts/traffic_light_evaluator_node.py
This PR enables to calculate correct distance from ego to traffic light.
[background]
Evaluator node calculate from ego to first traffic light(I mean first index) which is belong to regulatory element until now. If its traffic light is not minimum distance in regulatory element from ego, autoware can not be filterd by evaluator node's distance correctly.
I have checked it on [Evaluator](https://evaluation.ci.tier4.jp/evaluation/reports/b914f660-edd5-5ea1-9203-b261d6dac351?project_id=prd_jt).
There was intersection which is not calculated correctly, but I confirmed this PR enables to do correctly.
=> fix(traffic_light): enable to calculate correct distance from ego to traffic light

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.1.3

driving_log_replayer_v2/driving_log_replayer_v2/pose.py, driving_log_replayer_v2/test/unittest/test_pose.py
Address issue with decimals being cast as integers in Autoware Evaluator's scenario editor
Force an integer to be cast to a float
The dataset used for testing is TIER IV internal data.
```shell
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=$HOME/dlr2_data/all_component.yaml record_only:=true t4_dataset_path:=/home/hayatomizushima/.webauto/simulation/data/t4_dataset/prd_jt/f7effc57-f53a-41c9-9b8f-15c324dcda88/5/8599869c-ab32-4846-bd01-a220210f6c65/0 t4_dataset_id:=8599869c-ab32-4846-bd01-a220210f6c65 localization:=true planning:=true control:=true
```
before
```shell
[goal_pose_node.py-119]     position=Point(**pose_dict["position"]),
[goal_pose_node.py-119]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/geometry_msgs/msg/_point.py", line …
```
=> fix: convert int value to float

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2/test/unittest/test_pose.py, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.3.1

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> refactor: launch remap

driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- split bag operation
- split launch argument operation
=> refactor: bag operation

driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py, driving_log_replayer_v2/scripts/goal_pose_node.py, driving_log_replayer_v2/scripts/initial_pose_node.py
=> refactor: launch argument

docs/quick_start/installation.en.md, docs/quick_start/installation.ja.md
Due to yesterday's pull request 
- https://github.com/tier4/driving_log_replayer_v2/pull/109
we have to use driving_log_replayer_v2 with the latest autoware_tools.
This pull request adds instructions for importing `nightly.repos`.
=> docs: add instructions for importing nightly

driving_log_replayer_v2/driving_log_replayer_v2/launch/traffic_light.py
This PR change the topic to save in traffic_light. We cannot analyze from result using current topic to save, so I change to the topic which we can analyze.
- `/perception/traffic_light_recognition/traffic_signals/markers`      : the result of `autoware_traffic_light_map_visualizer`
- `/perception/traffic_light_recognition/.*/debug/rois/compressed` : the result of `autoware_traffic_light_roi_visualizer`
ref: https://github.com/autowarefoundation/autoware.universe/tree/main/perception/autoware_traffic_light_visualization
https://evaluation.ci.tier4.jp/evaluation/reports/fde6df31-c7ab-58b2-baa7-737c17aa4591?project_id=prd_jt
=> feat(traffic_light): change the topic to save

driving_log_replayer_v2/launch/post_process.launch.py
This PR enables to check pass/fail even if post-process is fail.
Before implementation, if post-process in perception is fail, Evaluator output pass because remain the jsonl which is produced by record_only mode driving_log_replayer_v2
https://evaluation.ci.tier4.jp/evaluation/reports/dc1001df-daa8-5ed3-9d56-384277f5eb5f?project_id=prd_jt
And, I check this PR remove the jsonl file (comment out the post-process)
=> feat(perception): check pass/fail even if post-process is fail

driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/evaluator.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/manager.py, driving_log_replayer_v2/driving_log_replayer_v2/perception_eval_conversions.py, sample/perception/scenario.fp.ja.yaml, sample/perception/scenario.fp.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml
This PR enables to evaluate prediction
reference : https://github.com/tier4/driving_log_replayer_v2/pull/40
- https://evaluation.ci.tier4.jp/evaluation/reports/95a1fe3a-6911-56bf-9739-43a8d3df6924?project_id=prd_jt
- https://evaluation.ci.tier4.jp/evaluation/reports/4e21761c-2b00-5a04-87de-388a9ec7031c?project_id=prd_jt
prediction result sample
```
Frame:
Total Num: 285
Skipped Frames: []
Skipped Frames Count: 0
Ground Truth Num: 154
ADE: 23.992, FDE: 47.849, Miss Rate: 0.909 (Miss Tolerance: 2.0[m])
|      Label | car(k=1) |  truck(k=1) |  bus(k=1) |  bicycle(k=1) |  motorbike(k=1) |  pedestrian(k=1) |
| :--------: | :---: | :---: | :---: | :---: | :---: | :---: |
| Predict_num | 162 | 0 | 0 | 0 | 0 | 0 |
|         ADE | 23.992 |  nan |  nan |  nan |  nan |  nan |
|         FDE | 47.849 …
```
=> feat(perception): add prediction evaluation

driving_log_replayer_v2/driving_log_replayer_v2/launch/localization.py
To parse `/localization/acceleration` in the scripts of `autoware_localization_evaluation_scripts`, this pull request add the topic to the record topic list.
- https://github.com/autowarefoundation/autoware_tools/pull/237
See
- https://github.com/autowarefoundation/autoware_tools/pull/237
=> fix: add `/localization/acceleration` into the record topic list

driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/runner.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/topics.py
This PR changes treat about empty string.
Regarding ROS 2 launch (like terminal), cannnot use empty string like `ros2 launch xxx xxx.launch.xml  parameter:=""`. So I allow to use "None" instead of "".
And previous code had spaces and line breaks so I modify it.
you can see https://github.com/tier4/pilot-auto/pull/1352
=> feat(perception): regular expression and the way to represent None

driving_log_replayer_v2/driving_log_replayer_v2/perception/manager.py
This PR get to change args `False` to `True` to save `scene_result.pkl`. (I made mistake in [this PR here](https://github.com/tier4/driving_log_replayer_v2/pull/143/files#diff-08f8b1136b01f45642920ce9d213c3917a76a43456c772bdf7bd9b8908bb1260))
=> fix(perception): change args `False` to `True` to save `scene_result.pkl`

driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py
=> feat: delete system defined remap

driving_log_replayer_v2/driving_log_replayer_v2/criteria/perception.py
This PR enables to use `get_num_gt()` of perception_eval.
perception_eval PR : https://github.com/tier4/autoware_perception_evaluation/pull/228
=> feat(perception): use function get_num_gt() of perception_eval

sample/perception/scenario.criteria.custom.yaml, sample/perception/scenario.fp.ja.yaml, sample/perception/scenario.fp.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml, sample/perception_2d/scenario.ja.yaml, sample/perception_2d/scenario.yaml
The new matching algorithm introduced in [PR](https://github.com/tier4/autoware_perception_evaluation/pull/225) enhances our framework significantly. If we opt for `ALLOW_UNKNOWN` as our matching policy, it is essential to specify the 'unknown' label in the target label for optimal performance.
To ensure a seamless integration and maximize the benefits of these improvements, this PR should be merged alongside this crucial [PR](https://github.com/tier4/autoware_perception_evaluation/pull/204).
=> chore: add unknown label

driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py
The original remapping doesn't work as expected because the `conf[goal_pose]` may not be None but a string `{}` in `planning_control` or `localization` scenarios
This PR fixes this problem.
=> fix(topic remapping): a bug of remapping regarding goal_pose

dependency.repos, driving_log_replayer_v2/test/unittest/test_perception.py, driving_log_replayer_v2/test/unittest/test_perception_2d.py, driving_log_replayer_v2/test/unittest/test_traffic_light.py, repository.cspell.json
This PR adds the `nuscene_object_results` in test code.
=> feat(perception): update test caused by adding the `nuscene_object_results` in perception_eval

driving_log_replayer_v2/CMakeLists.txt, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/models.py, driving_log_replayer_v2/driving_log_replayer_v2/publish_topic_from_rosbag.py, driving_log_replayer_v2/scripts/publish_topic_from_rosbag_node.py
This PR publishes the topic in rosbag as pre-task before play rosbag
sample command
```
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.xml scenario_path:=<path> dataset_index:=<index> remap_profile:=x2_perception publish_topic_from_rosbag:=/sensing/camera/camera0/camera_info,/sensing/camera/camera1/camera_info,/sensing/camera/camera2/camera_info,/sensing/camera/camera3/camera_info,/sensing/camera/camera4/camera_info,/sensing/camera/camera5/camera_info,/sensing/camera/camera6/camera_info,/sensing/camera/camera7/camera_info,/sensing/camera/camera8/camera_info,/sensing/camera/camera9/camera_info,/sensing/camera/camera10/camera_info
```
https://evaluation.ci.tier4.jp/evaluation/reports/2bbeba10-0f59-5234-8743-56a37bbf7d7f?project_id=prd_jt
=> feat: publish the topic in rosbag as pre-task before play rosbag

driving_log_replayer_v2/driving_log_replayer_v2/evaluator.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/planning_control.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/runner.py, driving_log_replayer_v2/driving_log_replayer_v2/result.py, driving_log_replayer_v2/scripts/annotationless_perception_evaluator_node.py, driving_log_replayer_v2/scripts/ar_tag_based_localizer_evaluator_node.py, driving_log_replayer_v2/scripts/diagnostics_evaluator_node.py, driving_log_replayer_v2/scripts/eagleye_evaluator_node.py, driving_log_replayer_v2/scripts/ground_segmentation_evaluator_node.py, driving_log_replayer_v2/scripts/localization_evaluator_node.py, driving_log_replayer_v2/scripts/obstacle_segmentation_evaluator_node.py, driving_log_replayer_v2/scripts/perception_2d_evaluator_node.py, driving_log_replayer_v2/scripts/performance_diag_evaluator_node.py, driving_log_replayer_v2/scripts/planning_control_evaluator_node.py, driving_log_replayer_v2/scripts/traffic_light_evaluator_node.py, driving_log_replayer_v2/scripts/yabloc_evaluator_node.py, sample/eagleye/scenario.yaml, sample/yabloc/scenario.yaml
Add options to publish the conditions and results to topics in real-time.
The content is identical to the JSON output and is published to the topic as `std_msgs/String.msg`.
Currently, I only use this feature in the `planning_control` use case.
```shell
~$ ros2 topic list | rg driving_log_replayer
/driving_log_replayer/diagnostics_results
/driving_log_replayer/metrics_results
~$ ros2 topic echo /driving_log_replayer/diagnostics_results
data: '{"Result": {"Success": true, "Summary": "Passed:Condition_0 (Success), Condition_1 (Success), Condition_2 (Success), Condition_3...'
---
data: '{"Result": {"Success": true, "Summary": "Passed:Condition_0 (Success), Condition_1 (Success), Condition_2 (Success), Condition_3...'
```
=> feat: publish conditions and results to topics

driving_log_replayer_v2/driving_log_replayer_v2/planning_control.py
I found a bug that when a planning_factor condition has `judgement == negative`, in other words, fails when a condition is met, should have the initial status `pass` because it should be pass if there is no any planning factor.
Run any scenario with `judgement==negative` that has a rosbag containing no planning factor messages.
=> fix(planning_control): a init bug of planning-factor result

driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py
P&C creates many scenarios from different products with different `vehicle_model` and `sensor_model` of rosbags.
When testing those scenarios in a different pilot-auto, we want to use the `vehicle_model` and `sensor_model` of that branch, so we want to assign `vehicle_model` and `sensor_model` by [.webauto-ci.yml](https://github.com/tier4/pilot-auto/compare/main...xtk/debug#diff-8c94ea7bde6e173c2d6b911ed85765005696d79fecdf11714848fb2186e0c1fb) like [this](https://github.com/tier4/pilot-auto/compare/main...xtk/debug#diff-8c94ea7bde6e173c2d6b911ed85765005696d79fecdf11714848fb2186e0c1fbR702-R703) 
This PR modifies the code to make such overwriting available.
=> feat: support override of vehicle_model and sensor_model

driving_log_replayer_v2/driving_log_replayer_v2/launch/obstacle_segmentation.py, driving_log_replayer_v2/driving_log_replayer_v2/obstacle_segmentation.py, driving_log_replayer_v2/scripts/obstacle_segmentation_evaluator_node.py, driving_log_replayer_v2/test/unittest/test_obstacle_segmentation.py
I optimize the visualization for obstacle_segmentation tests by:
- added map and ego topics to save for visualization
- modified markers in func `get_non_detection_area_in_base_link`
**This PR is created based on the branch [obstacle_segmentation_multipolygon](https://github.com/tier4/driving_log_replayer_v2/tree/exp/obstacle_segmentation_multipolygon)**
- This branch is for using multiple polygons for obstacle_segmentation tests, which is created by  @MyatmonThiri
- To @MyatmonThiri : I want to merge your branch and my updates to develop together. How do you think?
Parent JIRA ticket: https://tier4.atlassian.net/browse/T4DEV-31233
I ran the tests for two catalogs:
- https://evaluation.ci.tier4.jp/evaluation/reports/6349733c-0d97-56c4-8a6c-fe35224a0800?project_id=autoware_dev
- …
=> feat: better visualization for obstacle segmentation and support multipolygon

driving_log_replayer_v2/driving_log_replayer_v2/planning_control.py
When `factors` in the PlanningFactor message contain no factor, DLR will record nothing, just like that topic publishes nothing (≒ this module has died/doesn't work).
However, we want to distinguish these two situations (module didn't activate / module didn't work) when checking the DLR test results, so this PR lets the result of empty factors also be recorded in the result.
Evaluator: https://evaluation.tier4.jp/evaluation/reports/51f3c937-3b2a-5d62-8a9d-ee0f9073e7aa?project_id=x2_dev
Check a test_case's `planning_factor_result.jsonl`, most of lines sould be:
```
{"Result": {"Success": true, "Summary": "Passed:check run_out (Success)"}, "Stamp": {"System": 1759891594.758527, "ROS": 1754282426.3438594}, "Frame": {"check run_out": {"Result": {"Total": "Success", "Frame": "Success"}, …
```
=> chore(planning_control): output results when planning_factors is empt as well
