log_evaluator/log_evaluator/planning_control.py
=> style: replace kinetic with kinematic

log_evaluator/log_evaluator/planning_control.py
=> chore: add debug code

log_evaluator/CMakeLists.txt, log_evaluator/launch/log_evaluator.launch.py, log_evaluator/log_evaluator/evaluator.py, log_evaluator/log_evaluator/pose.py, log_evaluator/log_evaluator/scenario.py, log_evaluator/scripts/initial_pose_node.py
- Separated initial pose functionality from evelautor.py into an independent node.
=> feat: #11 split initial pose node

log_evaluator/launch/log_evaluator.launch.py
- To avoid import errors, only emit LogInfo when node startup is not required.
=> chore: not activate initial pose node

.vscode/settings.json, log_evaluator/CMakeLists.txt, log_evaluator/launch/log_evaluator.launch.py, log_evaluator/log_evaluator/pose.py, log_evaluator/scripts/goal_pose_node.py, log_evaluator/scripts/initial_pose_node.py
=> feat: #13 add goal pose node

log_evaluator/scripts/goal_pose_node.py, log_evaluator/scripts/initial_pose_node.py
=> refactor: delete unused variable

log_evaluator/scripts/goal_pose_node.py
=> refactor: delete unused code

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- create symlink to latest log directory
=> feat: create latest log directory symlink

driving_log_replayer_v2/driving_log_replayer_v2/performance_diag.py, sample/performance_diag/scenario.ja.yaml, sample/performance_diag/scenario.yaml
=> fix: update diag UseCaseFormatVersion

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> fix: path name to keep compatibility of v1

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> refactor: launch

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> fix: return dataset index

docs/overview/index.en.md, docs/overview/index.ja.md
=> docs: update annotation

docs/overview/command.en.md, docs/overview/command.ja.md
- add description of dlr2 command
=> docs: add description of dlr2 command

docs/scenario_format/index.en.md, docs/scenario_format/index.ja.md
=> docs: update format version

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> fix: remap topic to be unique

README.md
=> docs: update cli and shell completion

driving_log_replayer_v2/driving_log_replayer_v2/obstacle_segmentation.py, driving_log_replayer_v2/scripts/obstacle_segmentation_evaluator_node.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/__init__.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/__main__.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/analysis/__init__.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/analysis/obstacle_segmentation.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/config/__init__.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/config/obstacle_segmentation.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/data/__init__.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/data/obstacle_segmentation.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/plot/__init__.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/plot/bird_view_plot.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/plot/line_plot.py, driving_log_replayer_v2_analyzer/driving_log_replayer_v2_analyzer/plot/scatter_plot.py
=> fix: replace TierIV with TIER IV

driving_log_replayer_v2/driving_log_replayer_v2/launch/annotationless_perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/ar_tag_based_localizer.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/eagleye.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/localization.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/obstacle_segmentation.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception_2d.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/performance_diag.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/planning_control.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/traffic_light.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/yabloc.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- Support for launch argument used only in specific use cases
=> feat: add use case launch argument

docs/use_case/annotationless_perception.en.md, docs/use_case/annotationless_perception.ja.md, docs/use_case/ar_tag_based_localizer.en.md, docs/use_case/ar_tag_based_localizer.ja.md, docs/use_case/eagleye.en.md, docs/use_case/eagleye.ja.md, docs/use_case/localization.en.md, docs/use_case/localization.ja.md, docs/use_case/obstacle_segmentation.en.md, docs/use_case/obstacle_segmentation.ja.md, docs/use_case/perception.en.md, docs/use_case/perception.ja.md, docs/use_case/performance_diag.en.md, docs/use_case/performance_diag.ja.md, docs/use_case/planning_control.en.md, docs/use_case/planning_control.ja.md, docs/use_case/yabloc.en.md, docs/use_case/yabloc.ja.md
- replace C++ namespace `::` with python namespace `/`
=> style: document

docs/use_case/ar_tag_based_localizer.en.md, docs/use_case/ar_tag_based_localizer.ja.md, docs/use_case/eagleye.en.md, docs/use_case/eagleye.ja.md, docs/use_case/localization.en.md, docs/use_case/localization.ja.md, docs/use_case/performance_diag.en.md, docs/use_case/performance_diag.ja.md, docs/use_case/yabloc.en.md, docs/use_case/yabloc.ja.md
=> fix: service data type

docs/use_case/.pages, docs/use_case/index.en.md, docs/use_case/index.ja.md
=> docs: update index

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.0.0

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.0.1

.github/workflows/colcon-test.yaml
=> fix: trigger

driving_log_replayer_v2/test/unittest/test_annotationless_perception.py, driving_log_replayer_v2/test/unittest/test_localization.py, driving_log_replayer_v2/test/unittest/test_obstacle_segmentation.py, driving_log_replayer_v2/test/unittest/test_perception.py, driving_log_replayer_v2/test/unittest/test_perception_2d.py, driving_log_replayer_v2/test/unittest/test_result.py, driving_log_replayer_v2/test/unittest/test_traffic_light.py
=> fix: type hint

.vscode/settings.json, ReleaseNotes.md, dependency.repos, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2/driving_log_replayer_v2/lanelet2_util.py, driving_log_replayer_v2/package.xml, driving_log_replayer_v2/scripts/obstacle_segmentation_evaluator_node.py, driving_log_replayer_v2/test/unittest/test_lanelet2.py
- update library
- lanelet2_extension -> autoware_lanelet2_extension
=> feat: merge autoware lenelet2 extension

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
- release
- lanelet2_extension -> autoware_lanelet2_extension
=> chore: release 3.1.0

driving_log_replayer_v2/driving_log_replayer_v2/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/traffic_light.py, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml, sample/traffic_light/scenario.ja.yaml, sample/traffic_light/scenario.yaml
=> chore: update use case format version

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.1.2

.pre-commit-config.yaml, driving_log_replayer_v2/driving_log_replayer_v2/annotationless_perception.py, pyproject.toml
=> feat: update github actions

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.2.0

docs/use_case/.pages
=> docs: add ground_segmentation to index

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
- release(document deploy only)
=> chore: release 3.3.2

docs/overview/images/overview.drawio.svg
=> docs: update architecture

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.3.3

ReleaseNotes.md
=> docs: replace module all -> common

driving_log_replayer_v2/driving_log_replayer_v2/launch/all.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
- add all component evaluation
=> feat: all component test

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.4.0

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.4.1

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> refactor: launch const

driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py
=> refactor: launch argument

driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py
=> refactor: prepare paths

.github/workflows/colcon-test.yaml
=> chore: update github  actions for ros

driving_log_replayer_v2/scripts/obstacle_segmentation_evaluator_node.py
=> fix: initialization order

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.4.2

driving_log_replayer_v2/driving_log_replayer_v2/launch/ndt_convergence.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> feat: ndt convergence

driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py
=> refactor: output dummy result jsonl

driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py
=> refactor: remap operation

driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py, driving_log_replayer_v2/launch/driving_log_replayer_v2.launch.py, driving_log_replayer_v2/launch/post_process.launch.py, driving_log_replayer_v2/launch/pre-process.launch.py, driving_log_replayer_v2/launch/pre_process.launch.py, driving_log_replayer_v2/launch/simulation.launch.py, driving_log_replayer_v2/package.xml
- support localization post-process
update your autoware_tools <https://github.com/autowarefoundation/autoware_tools/pull/220>
```shell
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py scenario_path:=$HOME/dlr2_data/localization/scenario.yaml
```
- pre-process is only a template, not implemented
=> feat: support localization post process

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.6.1

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.6.2

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.6.3

driving_log_replayer_v2/driving_log_replayer_v2/performance_diag.py, driving_log_replayer_v2/test/unittest/test_performance_diag.py
Exclude data while initialization from performance diag total evaluation
TIER IV internal
Result Comparison:
Before: https://evaluation.tier4.jp/evaluation/reports/42cf03d9-e6ea-5112-839f-b2d47d758d38/tests/a39eafe0-08e8-5bbc-bf90-1875ee058d27/fa324ff9-f892-5a2d-917b-702d75395646/512472de-64b8-560c-942d-ba3e8a6757a2?project_id=x2_dev
After: https://evaluation.tier4.jp/evaluation/reports/a831b74b-294f-5b4c-883b-65640859d9f2/tests/920bf370-ab09-581e-8fd5-96526666eb04/4d77400f-3647-5193-88b2-8461c8c3ec20?project_id=x2_dev
=> feat: exclude data while initialization from performance diag total evaluation

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml, repository.cspell.json
=> chore: release 3.6.4

docs/use_case/.pages, docs/use_case/all_components.ja.md, docs/use_case/all_components.md, docs/use_case/index.en.md, docs/use_case/index.ja.md, sample/all_components/result.json, sample/all_components/scenario.yaml
=> docs: all_components

.pre-commit-config.yaml, driving_log_replayer_v2/driving_log_replayer_v2/criteria/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/obstacle_segmentation.py, driving_log_replayer_v2/driving_log_replayer_v2/perception_eval_conversions.py, pyproject.toml
- update ruff version
- update pre-commit tool version
=> chore: update tool version

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.6.5

driving_log_replayer_v2/driving_log_replayer_v2/evaluator.py, driving_log_replayer_v2/scripts/perception_2d_evaluator_node.py
=> fix: delete duplicated method

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.7.0

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.7.1

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.7.2

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.7.3

driving_log_replayer_v2/driving_log_replayer_v2/perception/runner.py, driving_log_replayer_v2/launch/post_process.launch.py
This PR enables to use storage_option like mcap etc.
I checked this PR w/ storage:=mcap on my local pc.
=> feat(perception): handle storage options

driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py
- change rosbag record default format db3 -> mcap
=> feat: set mcap as default

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.8.0

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.8.1

docs/overview/index.en.md, docs/overview/index.ja.md
=> docs: fix cover range

driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/analyze.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/runner.py, driving_log_replayer_v2/launch/post_process.launch.py
This PR gets to add args `max_distance` and `distance_interval`. (It is ok that changing 150 
to 100 bacause I want to reduce calcuration time)
https://evaluation.ci.tier4.jp/evaluation/reports/312ecc17-014f-592d-adb9-97b02533ea8f?project_id=prd_jt
=> feat(perception): add args range

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.8.2

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.8.3

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: 3.8.4

driving_log_replayer_v2_cli/core/result.py
=> perf: Improved memory usage

driving_log_replayer_v2/driving_log_replayer_v2/result.py
=> feat: add ResultReader

driving_log_replayer_v2/driving_log_replayer_v2/result.py
=> feat: ResultEditor

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.10.0

driving_log_replayer_v2/package.xml, driving_log_replayer_v2_analyzer/package.xml, driving_log_replayer_v2_msgs/package.xml
This PR adds Masato Saeki as maintainer and remove Minoda-san as it.
=> feat: remove minoda-san and add saeki as maintainer

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.10.1

driving_log_replayer_v2/driving_log_replayer_v2/perception_eval_conversions.py
This PR addresses [the new PR](https://github.com/tier4/autoware_perception_evaluation/pull/218) in `perception_eval`.
I tested on the cloud evaluator: [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/0351f8a9-32d8-50f2-ab89-c41e01b9a72b?project_id=prd_jt)
=> feat: add timestamps for predicted path

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.10.2

docs/use_case/perception.en.md, docs/use_case/perception.ja.md
Add more detailed instructions to help users correctly start the perception evaluation process.
=> chore(documentation): update perception evaluation tutorial

.pre-commit-config.yaml, driving_log_replayer_v2/driving_log_replayer_v2/perception_eval_conversions.py, driving_log_replayer_v2/driving_log_replayer_v2/result.py, driving_log_replayer_v2/driving_log_replayer_v2/scenario.py, driving_log_replayer_v2/test/unittest/test_evaluator.py, driving_log_replayer_v2/test/unittest/test_obstacle_segmentation.py, driving_log_replayer_v2_cli/test/simulation/test_run.py, pyproject.toml, uv.lock
=> feat: update ruff version

driving_log_replayer_v2/test/unittest/test_perception.py, sample/perception/scenario.criteria.custom.yaml, sample/perception/scenario.ja.yaml, sample/perception/scenario.yaml
This PR fixes scenario file in perception.
=> fix(perception): fix scenario for perception

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.11.0

driving_log_replayer_v2/driving_log_replayer_v2/perception/evaluator.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/manager.py
This PR handles with TrackedObjects and PredictedObjects type in fp validation
[TIER IV INTERNAL LINK
](https://star4.slack.com/archives/C02G6HT8TNX/p1752822393496739?thread_ts=1749801871.011349&cid=C02G6HT8TNX)
=> feat(perception): handle TrackedObjects and PredictedObjects type in fp validation

driving_log_replayer_v2/driving_log_replayer_v2/lanelet2_util.py
This PR supports multiple map projector.
Only check the degradation for TLR : https://evaluation.ci.tier4.jp/evaluation/reports/f409255c-7570-5ae1-bbb1-9111a76d0620?project_id=prd_jt
Only check the degradation for perception : https://evaluation.ci.tier4.jp/evaluation/reports/f93cf4ce-bfb3-5cdf-80a8-a28593f7e126?project_id=prd_jt
=> feat(lanelet): support multiple map projector

driving_log_replayer_v2/driving_log_replayer_v2/criteria/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/runner.py, driving_log_replayer_v2/test/unittest/test_perception_2d.py
Changes that need to merge with https://github.com/tier4/autoware_perception_evaluation/pull/204
=> chore(Metric Score): fix variable name

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.11.1

driving_log_replayer_v2/driving_log_replayer_v2/lanelet2_util.py
This PR adds support for loading maps defined in the **TM (Transverse Mercator) coordinate system**.
A new map loader has been implemented (or extended) to handle TM coordinates correctly and convert them as needed for internal use.
* Check the new/updated map loading logic that handles TM coordinates.
* Verify that maps using TM coordinates are parsed and displayed correctly.
* Confirm that existing (non-TM) maps still work as expected (no regression).
* Review unit tests (if added) for TM coordinate support.
* Please share any suggestions on optimizing the coordinate conversion if needed.
=> feat(lanelet): support TM-based map loading

driving_log_replayer_v2/driving_log_replayer_v2/planning_control.py, sample/planning_control/scenario.yaml, sample/planning_control/scenario_aeb_only.yaml, sample/planning_control/scenario_diag_only.yaml, sample/planning_control/scenario_planning_factor_only.yaml
This PR upgrate the UsaCaseFormatVersion for pc
=> feat(planning_control): update format version for planning_control

driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/perception/runner.py, driving_log_replayer_v2/launch/post_process.launch.py
This PR adds arguments `enable_analysis` to enable analysis
=> feat(perception): add args to enable analysis

driving_log_replayer_v2/driving_log_replayer_v2/launch/localization.py, driving_log_replayer_v2/launch/post_process.launch.py
This PR adds args to swtich to enable to use localization analysis in post-process
=> feat(localization): add args to switch to enable to use localization analysis in post-process

driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py
This PR remove the unnecessary args.
=> chore(perception): remove unnecessary args

ReleaseNotes.md, driving_log_replayer_v2/CHANGELOG.rst, driving_log_replayer_v2_analyzer/CHANGELOG.rst, driving_log_replayer_v2_msgs/CHANGELOG.rst, pyproject.toml
=> chore: release 3.13.2

docs/use_case/performance_diag.en.md, docs/use_case/performance_diag.ja.md, driving_log_replayer_v2/driving_log_replayer_v2/performance_diag.py, driving_log_replayer_v2/scripts/performance_diag_evaluator_node.py, driving_log_replayer_v2/test/unittest/test_performance_diag.py
This PR adopts the diag name and value in performance_diag scenario caused by following things.
- https://github.com/tier4/autoware_universe/pull/2350
- https://github.com/tier4/aip_launcher/pull/557
- https://github.com/tier4/aip_launcher/pull/561
=> feat(performance_diag): adopt new diag msg

driving_log_replayer_v2/driving_log_replayer_v2/launch/ndt_convergence.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/util.py, driving_log_replayer_v2/launch/post_process.launch.py
This PR is re-implemented instead of https://github.com/tier4/driving_log_replayer_v2/pull/229
https://evaluation.tier4.jp/evaluation/reports/42ab8d3a-2856-574b-8be9-4f79467c9f57?project_id=autoware_dev
=> fix(ndt_convergence): create valid rosbag

driving_log_replayer_v2/driving_log_replayer_v2/launch/all_components.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/annotationless_perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/ar_tag_based_localizer.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/argument.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/diagnostics.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/eagleye.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/ground_segmentation.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/localization.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/ndt_convergence.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/obstacle_segmentation.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/perception_2d.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/performance_diag.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/planning_control.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/traffic_light.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/use_case.py, driving_log_replayer_v2/driving_log_replayer_v2/launch/yabloc.py
=> refactor: refactor arguments and get method in context

driving_log_replayer_v2/driving_log_replayer_v2/launch/rosbag.py
This refactoring (https://github.com/tier4/driving_log_replayer_v2/pull/226/commits/239268812878801cd2658be0493a3d35b81f7c10#diff-9f182d47bf16b112e383a10bcbb28cbfcb1575c425346a44e10db19ebe152b24R50) made a bug in the previous PR.
=> fix(rosbag): profile func bug
